### ISSUE TITLE
PDF is not displayed if Text is not published

### ISSUE THREAD

**Issue by jerico** [younginnovations/resourcecontracts-api#8]
Currently in contract document viewer, when a contract don't have it's "Text" published there's will be an error loading even the PDF.

We'd like to request to make PDF still be able to be viewed even if "Text" is in draft.

**Comment by anjesh** [comment]
You have to publish the "Text" to load the PDF because the system was designed that way in the beginning. However we introduced "Show Pdf Text" to hide the text to mitigate the issue of improper OCR text. You have to untick "Show Pdf Text" and then text will not be sent through API, you may handle that blank text value to show appropriate message in the viewer then. 

![image](https://cloud.githubusercontent.com/assets/120488/10563655/fe55d668-75b0-11e5-990e-9c24e9b9e892.png)

**Comment by jerico** [comment]
This is fixed. Thanks
